releases:
- name:    bosh-dns-aliases
  version: "0.0.4"
  sha1:    sha256:27ef8965dc4f1633479613743e782566e3b7fba5d28dad3d50488c2919eac0da
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=" releases.bosh-dns-aliases.version ))
